### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by jens-a-e** [muthesius/64bit#1]
How to structure the content of this repo is the first issue 😄 

@medienJan & @teja-m please fork this repository and for the cubes, please make a folder called `cubes`, then open a PR, the rest ist Github workflow as usual.

Any thoughts?

**Comment by medienJan** [comment]
Sorry for directly pushing the code. It was not possible to fork.

**Comment by jens-a-e** [comment]
Compile works, project repo has some code, I think we can close this one 👍
